##
## META-INF/thirdcoast/defaults.toml
##

[THIRDCOAST.WHEEL]
  ticksPerRevolution         = 4096
  driveSetpointMax           = 0
  azimuthControlMode         = "MotionMagic"
  driveOpenLoopControlMode   = "PercentOutput"
  driveClosedLoopControlMode = "Velocity"

[THIRDCOAST.SWERVE]
  enableGyroLogging = true
  length = 1.0
  width  = 1.0

[THIRDCOAST.TALONS]
  timeout = 10
